// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("solace")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/solacereceiver"
)

const (
	TracesStability = component.StabilityLevelBeta
)
