// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("purefb")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/purefbreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
