// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("azureauth")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/extension/azureauthextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
