// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ecs_task_observer")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/extension/observer/ecstaskobserver"
)

const (
	ExtensionStability = component.StabilityLevelUnmaintained
)
