// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("gitlab")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/gitlabreceiver"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
