// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("failover")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/connector/failoverconnector"
)

const (
	TracesToTracesStability   = component.StabilityLevelAlpha
	MetricsToMetricsStability = component.StabilityLevelAlpha
	LogsToLogsStability       = component.StabilityLevelAlpha
)
