// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8sobjects")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)
