// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("rabbitmq")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/rabbitmqreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
