// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("github")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/githubreceiver"
)

const (
	TracesStability  = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelAlpha
)
