// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oracledb")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/oracledbreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
