// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("zipkin")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/zipkinreceiver"
)

const (
	TracesStability = component.StabilityLevelBeta
)
