// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("cgroupruntime")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/extension/cgroupruntimeextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
