// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sqlquery")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/sqlqueryreceiver"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelAlpha
)
