// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8slog")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/k8slogreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
