// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("http_forwarder")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/extension/httpforwarderextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
