// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("systemd")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/systemdreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
