// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("loki")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/lokireceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
