// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("libhoney")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/receiver/libhoneyreceiver"
)

const (
	TracesStability = component.StabilityLevelAlpha
	LogsStability   = component.StabilityLevelAlpha
)
