// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awslogs_encoding")
	ScopeName = "github.com/andresousafd/opentelemetry-collector-contrib/extension/encoding/awslogsencodingextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
